service: chameleon-api

custom:
  stage: ${env:STAGE, self:provider.stage}
  ml_eventbus_name: modelDeploy-${self:custom.stage}
  ml_eventbus_arn: arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/${self:custom.ml_eventbus_name}
  state_machine_model_deployment: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:custom.stage}PythonModelDeployment
  logRetentionInDays: 365
  dotenv:
    exclude:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - JWT_SECRET

provider:
  name: aws
  stage: ${env:STAGE, 'dev'}
  runtime: nodejs12.x
  environment:
    # JWT conf
    JWT_TTL_SECONDS: ${env:JWT_TTL_SECONDS}
    JWT_SECRET: ${ssm:/chameleon/jwt-${self:custom.stage}}

    # Chameleon Bucket
    BUCKET: ${env:BUCKET}

    # Chameleon clients db table
    CHAMELEON_PROJECTS_TABLE: ${env:CHAMELEON_PROJECTS_TABLE}
    CHAMELEON_APP_LOGS_TABLE: ${env:CHAMELEON_APP_LOGS_TABLE}
    CHAMELEON_APP_MONITOR_TABLE: ${env:CHAMELEON_APP_MONITOR_TABLE}

    # MongoDB
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    MONGO_DB_PROTOCOL: ${env:MONGO_DB_PROTOCOL}
    MONGO_DB_USER: ${env:MONGO_DB_USER}
    MONGO_DB_PASS: ${env:MONGO_DB_PASS}
    MONGO_DB_NAME: ${env:MONGO_DB_NAME}

    # Chameleon State Machine
    STATE_MACHINE_MODEL_DEPLOY: ${self:custom.state_machine_model_deployment}
    ML_EVENT_BUS: ${self:custom.ml_eventbus_name}

  iamRoleStatements: ${file(resources/roles.yml)}

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-log-retention
  - serverless-step-functions
package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - projects/**
    - resources/**
    - docker-images/**
    - dist/**/*.map
    - node_modules/aws-sdk/**
    - nodemon.json
    - README.md

functions:
  - ${file(resources/functions/chameleon-api.yml)}
  - ${file(resources/functions/chameleon-uploader.yml)}
  - ${file(resources/functions/chameleon-saver.yml)}
  - ${file(resources/functions/chameleon-model-deploy.yml)}
  - ${file(resources/functions/chameleon-model-destroy.yml)}
  - ${file(resources/functions/chameleon-model-on-deploy.yml)}
  - ${file(resources/functions/chameleon-model-on-error.yml)}
  - ${file(resources/functions/chameleon-model-on-sf-error.yml)}

stepFunctions:
  stateMachines:
    PythonModelDeployment: ${file(resources/state-machines/chameleon-model-deploy.yml)}

resources:
  - ${file(resources/elements.yml)}
