Resources:
  BatchCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:provider.environment.CACHE_TABLE_NAME}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: createdAt
        Enabled: true
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
